const menu = [
  {
    id: 1,
    title: "ผัดไทยกุ้งสด",
    category: "อาหารจานเดียว",
    price: 49.0,
    img: "https://www.unileverfoodsolutions.co.th/dam/global-ufs/mcos/SEA/calcmenu/recipes/TH-recipes/pasta-dishes/%E0%B8%9C%E0%B8%B1%E0%B8%94%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%81%E0%B8%B8%E0%B9%89%E0%B8%87%E0%B8%AA%E0%B8%94/%E0%B8%9C%E0%B8%B1%E0%B8%94%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%81%E0%B8%B8%E0%B9%89%E0%B8%87%E0%B8%AA%E0%B8%94_header.jpg",
    desc: `ผัดไทยเส้นจันท์เหนียวนุ่ม กุ้งสดตัวโต โรยถั่วบดหอม ๆ เสิร์ฟพร้อมมะนาวและผักสด.`,
  },
  {
    id: 2,
    title: "ข้าวกระเพราหมูกรอบ",
    category: "อาหารจานเดียว",
    price: 55.0,
    img: "https://recipe.sgethai.com/wp-content/uploads/2025/06/130625-crispy-pork-belly-with-thai-basil-cover.webp",
    desc: `หมูกรอบผัดกับใบกะเพราและพริกสด รสจัดจ้านหอมกลิ่นกระเพราแท้.`,
  },
  {
    id: 3,
    title: "ต้มยำกุ้ง",
    category: "อาหารไทยแท้",
    price: 79.0,
    img: "https://www.thaiholidayguide.com/wp-content/uploads/2022/12/cok2-1.jpg",
    desc: `ต้มยำรสเข้มข้น ซดร้อน ๆ มีกลิ่นสมุนไพรไทยและกุ้งสดเด้ง ๆ.`,
  },
  {
    id: 4,
    title: "ข้าวมันไก่",
    category: "อาหารจานเดียว",
    price: 45.0,
    img: "https://img.wongnai.com/p/1920x0/2017/06/22/bbf899f7ab4341dea4aec6330c2afafd.jpg",
    desc: `ข้าวหอมมัน เสิร์ฟพร้อมไก่ต้มเนื้อนุ่มและน้ำจิ้มเต้าเจี้ยวสูตรเด็ด.`,
  },
  {
    id: 5,
    title: "แกงเขียวหวานไก่",
    category: "อาหารไทยแท้",
    price: 65.0,
    img: "https://recipe.sgethai.com/wp-content/uploads/2025/02/030225-chicken-green-curry-cover.webp",
    desc: `แกงเขียวหวานหอมกะทิสด รสกลมกล่อม เสิร์ฟพร้อมข้าวสวยร้อน ๆ.`,
  },
  {
    id: 6,
    title: "ส้มตำไทย",
    category: "อาหารอีสาน",
    price: 40.0,
    img: "https://f.ptcdn.info/645/047/000/ohl4zjyn4DbiuAARqzW-o.jpg",
    desc: `ส้มตำรสจัด เปรี้ยว หวาน เค็ม เผ็ด ครบรส พร้อมถั่วลิสงคั่วหอม ๆ.`,
  },
  {
    id: 7,
    title: "ลาบหมู",
    category: "อาหารอีสาน",
    price: 50.0,
    img: "https://www.unileverfoodsolutions.co.th/dam/global-ufs/mcos/SEA/calcmenu/recipes/TH-recipes/red-meats-&-red-meat-dishes/%E0%B8%A5%E0%B8%B2%E0%B8%9A%E0%B8%AB%E0%B8%A1%E0%B8%B9/%E0%B8%A5%E0%B8%B2%E0%B8%9A%E0%B8%AB%E0%B8%A1%E0%B8%B9_header.jpg",
    desc: `ลาบหมูรสแซ่บ หอมข้าวคั่วและพริกป่น เสิร์ฟพร้อมผักสด.`,
  },
  {
    id: 8,
    title: "ข้าวผัดกุ้ง",
    category: "อาหารจานเดียว",
    price: 55.0,
    img: "https://recipe.sgethai.com/wp-content/uploads/2025/04/250425-Shrimp-Fried-Rice-cover.webp",
    desc: `ข้าวผัดกุ้งเนื้อเด้ง ผัดหอมกลิ่นกระเทียม เสิร์ฟร้อน ๆ พร้อมแตงกวาและมะนาว.`,
  },
  {
    id: 9,
    title: "หมูสะเต๊ะ",
    category: "ของกินเล่น",
    price: 45.0,
    img: "https://img.wongnai.com/p/1920x0/2018/10/31/52a20e563de44402b0ea7483039cd3db.jpg",
    desc: `หมูสะเต๊ะหอมเครื่องเทศ เสิร์ฟพร้อมน้ำจิ้มถั่วและอาจาด.`,
  },
];

export default menu;
